### ISSUE TITLE
"Place Order" button does nothing.

### ISSUE THREAD

**Issue by thomas-harding** [Worldpay/Worldpay-Magento2-CG#24]
I've installed this extension on a Magento 2.3.2 platform. 

Mode: Test
Credit Cards: Enabled
Integration Mode: Direct
PHP Version: 7.1.3.2

When I populate the credit card form with test card details and press "Place Order" absolutely nothing happens. No console errors, nothing in the logs. The button does absolutely nothing.

I've changed the Magento theme to Luma to see if the issue is resolved, the same happens.

Please advise?

**Comment by elavarasann** [comment]
Please make sure that if 3DS2 configuration is enabled in admin then all the fields belong to 3DS2 should not be empty. If your merchant account doesn't have to 3DS2 details then please disable from admin. PFA for your reference. For more details please check the user doc.

![wp-error](https://user-images.githubusercontent.com/5245575/65432032-1e560700-de38-11e9-894c-af83e1c874bf.png)

**Comment by too-dark-park** [comment]
Just in case it helps anyone else - we also had the same issue where the button appeared enabled but didn't appear to do anything when clicked. 

Sapient Worldpay: 1.5.2
Magento 2: 2.2.3
Mode: Test
Credit Cards: Enabled
Integration Mode: Direct

The reason was because a direct integration needed the following config:

Client Side Encryption Enabled: Yes
Public Key: <from worldpay>

JS Function: preparePayment

`if (this.isClientSideEncryptionEnabled() && this.intigrationmode == 'direct') {`

```
            isClientSideEncryptionEnabled:function(){
                if (this.getCsePublicKey()) {
                    return window.checkoutConfig.payment.ccform.cseEnabled;
                }
                return false;
```

**Comment by elavarasann** [comment]
This issue has been fixed, hence closing this.
