### ISSUE TITLE
Worldpay enabled 3D Secure enabled error

### ISSUE THREAD

**Issue by eross1lf** [Worldpay/Worldpay-Magento2-CG#31]
Hi, 

Current module version: 2.1.5 
We have enabled the 3D secure in Worldpay and some issues started to show in the module

1. In a relative busy day we have around 200 occurrences of the error:
Uncaught Error: Call to a member function getEchoData() on null in app/code/Sapient/Worldpay/Model/Authorisation/ThreeDSecureService.php:56 

2. Duplicate orders have been placed 

Could you please tell me if you have any other customers complaining of the same issue after enabling the 3D secure check?

Also is the module 3DS2 ready? Is there anything we need to set for this to work?

**Comment by chandan-PS** [comment]
Hi @eross1lf 

We need to look in to this. We suspect this is happening because Chrome 80 has added a new cookie.

We have added the fix in our current release (q2.20.v2.3.4). If required we can share the patch as well.

On the question of 3DS2 - Yes, 3DS2 is stable from our version 2.1.7, let us know, if you face any challenge.

**Comment by eross1lf** [comment]
Hi Chandan,

Please share the patch. 
Hope this will fix our error.

**Comment by chandan-PS** [comment]
HI @eross1lf - I have sent you the patch in email, please confirm if you have received it.

**Comment by chandan-PS** [comment]
Closing this issue for now, let us know if you any other issues.
