### ISSUE TITLE
Column not found: 1054 Unknown column 'risk_provider_final' in 'worldpay_payment'

### ISSUE THREAD

**Issue by rougiain** [Worldpay/Worldpay-Magento2-CG#6]
Issue when installing via  setup:upgrade

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'risk_provider_final' in 'worldpay_payment'

Magento 2.2

**Comment by lochansim** [comment]
Thanks for getting in touch directly too. We are investigating. We'll respond directly and if anything needs updating on the plugin we'll release for the whole community

**Comment by bmitchell-ldg** [comment]
Hi, we also had this issue, because they have used the same database table name worldpay_payment in the old worldpay setup, and the new sapient version, and when raising it with our account manager we were told it is not possible to run the old module and the new one concurrently. 
We had to build a module to rename the worldpay_payment table and disable the old version, and then when you re-run setup:upgrade it installs correctly.
It could possibly be the same issue so i thought i would mention it, hope this helps.
